In [1]:
import numpy as np 
import pandas as pd 
import os

In [20]:
import sklearn
from sklearn import linear_model
import pickle
print(sklearn.__version__)

1.3.2


In [10]:
data_file = pd.read_csv('student-mat.csv', sep=";")

In [19]:
print(data_file.shape)
print(data_file.head)

(395, 5)
<bound method NDFrame.head of      studytime  failures  absences  G2  G3
0            2         0         6   6   6
1            2         0         4   5   6
2            2         3        10   8  10
3            3         0         2  14  15
4            2         0         4  10  10
..         ...       ...       ...  ..  ..
390          2         2        11   9   9
391          1         0         3  16  16
392          1         3         3   8   7
393          1         0         0  12  10
394          1         0         5   9   9

[395 rows x 5 columns]>


In [12]:
data_file.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')

In [13]:
data_file = data_file[[#'school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       #'Mjob', 'Fjob', 'reason', 'guardian', 
            #'traveltime', 
             'studytime',
       'failures', #'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       #'higher', 'internet', 'romantic', 'famrel', 
    #'freetime', 'goout', 'Dalc',
       #'Walc', 'health', 
    'absences', #'G1', 
    'G2', 
    'G3']]

In [14]:
data_file['studytime'].value_counts()

studytime
2    198
1    105
3     65
4     27
Name: count, dtype: int64

In [15]:
data_file.columns

Index(['studytime', 'failures', 'absences', 'G2', 'G3'], dtype='object')

In [16]:
predict = "G3"

X = np.array(data_file.drop([predict], axis=1))
y = np.array(data_file[predict])

x_train, x_test, y_train, y_test = sklearn.model_selection.train_test_split(X, y, test_size=0.2)
print(x_train)
linear = linear_model.LinearRegression()
linear.fit(x_train, y_train)
acc = linear.score(x_test, y_test)
print(acc)

with open("gradepredictor.pickle", "wb") as f:
    pickle.dump(linear, f)

[[ 2  0  2 10]
 [ 2  0  4 10]
 [ 3  0  6  7]
 ...
 [ 2  1  0 10]
 [ 2  0 20 12]
 [ 2  0  4 11]]
0.8850881244755914


In [17]:
gradepredictor_pickle = open("gradepredictor.pickle", "rb")
gradepredictor_model = pickle.load(gradepredictor_pickle)
new_data = np.array([[4, 0, 30, 12]]) #studytime_value, failures_value, absences_value, G2_value
prediction = gradepredictor_model.predict(new_data)
print(prediction)

[12.66656317]


In [23]:
# data_heatmap = data_file.corr()
# data_heatmap

In [ ]:
# sns.heatmap(data_heatmap, annot=True)